import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');

const desktopHtml = readFileSync(path.resolve(root, 'dist/desktop/index.html'), 'utf8');

const mobileHtmlPath = path.resolve(root, 'dist/mobile/index.mobile.html');
const mobileHtmlFallbackPath = path.resolve(root, 'dist/mobile/index.html');
const hasMobileBuild = existsSync(mobileHtmlPath) || existsSync(mobileHtmlFallbackPath);

const verifyLocalMobileAssets = (html: string) => {
  const assetReferences = [...html.matchAll(/(?:src|href)="([^"]+)"/g)]
    .map((match) => match[1])
    .filter((reference) => /\.(?:css|js)(?:[?#].*)?$/.test(reference));

  if (assetReferences.length === 0) {
    throw new Error('Mobile SPA template does not reference any JavaScript or CSS assets');
  }

  for (const reference of assetReferences) {
    if (!reference.startsWith('/_spa/')) {
      throw new Error(`Mobile SPA asset must use the local /_spa/ path: ${reference}`);
    }

    const localPath = path.resolve(root, 'public', reference.slice(1).split(/[?#]/, 1)[0]);
    if (!existsSync(localPath)) {
      throw new Error(`Mobile SPA asset is missing from public/_spa: ${reference}`);
    }
  }
};

let output: string;

if (hasMobileBuild) {
  // Docker: mobile build exists locally, inline the template
  const mobileHtml = readFileSync(
    existsSync(mobileHtmlPath) ? mobileHtmlPath : mobileHtmlFallbackPath,
    'utf8',
  );
  verifyLocalMobileAssets(mobileHtml);

  output = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

export const desktopHtmlTemplate = ${JSON.stringify(desktopHtml)};

export const mobileHtmlTemplate = ${JSON.stringify(mobileHtml)};
`;
} else {
  // Vercel: no mobile build, import from pre-committed source file
  output = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

import { mobileHtmlTemplate } from './mobileHtmlTemplate.source';

export const desktopHtmlTemplate = ${JSON.stringify(desktopHtml)};

export { mobileHtmlTemplate };
`;
}

writeFileSync(
  path.resolve(root, 'src/app/spa/[variants]/[[...path]]/spaHtmlTemplates.ts'),
  output,
  'utf8',
);

console.log(`Generated spaHtmlTemplates.ts (mobile from ${hasMobileBuild ? 'build' : 'source'})`);

const authHtmlPath = path.resolve(root, 'dist/auth/index.auth.html');

if (existsSync(authHtmlPath)) {
  const authHtml = readFileSync(authHtmlPath, 'utf8');

  const authOutput = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

export const authHtmlTemplate = ${JSON.stringify(authHtml)};
`;

  writeFileSync(path.resolve(root, 'src/app/spa-auth/authHtmlTemplate.ts'), authOutput, 'utf8');

  console.log('Generated authHtmlTemplate.ts');
} else {
  console.log('Skipped authHtmlTemplate.ts (no dist/auth build)');
}
